# Generated by Django 4.0.6 on 2024-01-19 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('streetvigil', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='capturedimage',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='capturedimage',
            name='category',
            field=models.CharField(choices=[('CR', 'Crime'), ('AC', 'Accident'), ('SA', 'Suspicious Activity'), ('LF', 'Lost and Found'), ('OT', 'Other')], default='OT', max_length=2),
        ),
        migrations.AddField(
            model_name='capturedimage',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='capturedimage',
            name='description',
            field=models.TextField(default='No description provided'),
        ),
        migrations.AddField(
            model_name='capturedimage',
            name='reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='capturedimage',
            name='image',
            field=models.ImageField(upload_to='captured_images/'),
        ),
    ]
