# Generated by Django 5.0.1 on 2024-01-20 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streetvigil', '0006_alter_capturedimage_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='capturedimage',
            name='status',
            field=models.CharField(default='P', max_length=4),
        ),
    ]
