# Generated by Django 5.0.1 on 2024-01-20 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streetvigil', '0007_capturedimage_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capturedimage',
            name='rewards',
            field=models.FloatField(default=0),
        ),
    ]
